server.port=8080

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

management.endpoints.web.exposure.include=*

spring.cloud.gateway.server.webmvc.routes[0].id=ms-productos
spring.cloud.gateway.server.webmvc.routes[0].uri=http://ms-productos:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/productos/**

spring.cloud.gateway.server.webmvc.routes[1].id=ms-inventario
spring.cloud.gateway.server.webmvc.routes[1].uri=http://ms-inventario:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/inventario/**